language: csharp
mono: none
dotnet: 3.1
branches:
  only:
    - blazor
script:
  - dotnet publish -c Release -o ./publish

deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  edge: true
  target_branch: master
  fqdn: stevendirth.com
  committer_from_gh: true
  local_dir: ./publish
  on:
    branch: blazor