language: node_js
node_js:
  - "10"
cache: npm
dist: trusty

branches:
  only:
  - source
before_script:
  - npm install -g angular-cli-ghpages
script:
  - ng build --prod --base-href https://stevendirth.com/
  - ngh --dir=dist/personal-website-seven --repo=https://$GITHUB_TOKEN@github.com/dirthsj/dirthsj.github.io.git --branch master --cname stevendirth.com