language: csharp
mono: none
dotnet: 3.1
branches:
  only:
    - blazor
script:
  - dotnet publish -c Release -o ./publish
  - git config --global user.name "$NAME"
  - git config --global user.email "$EMAIL"

deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  edge: true
  target_branch: master
  fqdn: stevendirth.com
  committer_from_gh: true
  on:
    branches:
      only:
        - blazor