dist: bionic
sudo: false

language: node_js
node_js:
  - '14'

cache:
  directories:
    - ./node_modules

install:
  - npm install

before_script:
  - npm install -g @angular/cli@10

script:
  - ng build --prod --deploy-url https://stevendirth.com/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  local_dir: dist/StevenDirth/
  target_branch: master
  fqdn: stevendirth.com
  on:
    branch: angular
