language: csharp
mono: none
dotnet: 3.1
branches:
  only:
    - blazor
script:
  - dotnet publish -c Release -o ./publish
  - touch ./publish/wwwroot/.nojekyll

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: false
  target_branch: master
  fqdn: stevendirth.com
  committer_from_gh: true
  local_dir: ./publish/wwwroot
  on:
    branch: blazor